module.exports = {
  apps: [
    {
      name: 'mydeadinternet',
      script: '/var/www/mydeadinternet/server.js',
      cwd: '/var/www/mydeadinternet',
      autorestart: true,
      max_memory_restart: '800M',
      time: true,
      env: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'mdi-feeds',
      script: '/var/www/mydeadinternet/mdi-feeds.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: true,
      max_memory_restart: '600M',
      time: true,
    },
    {
      name: 'mdi-dlq-retry',
      script: '/var/www/mydeadinternet/scripts/dlq-retry.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: true,
      max_memory_restart: '300M',
      time: true,
    },
    {
      name: 'mdi-pulse',
      script: '/var/www/mydeadinternet/pulse-generator.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: true,
      max_memory_restart: '300M',
      time: true,
    },
    {
      name: 'mdi-claims-creator',
      script: '/var/www/mydeadinternet/claim-auto-creator.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: true,
      max_memory_restart: '300M',
      time: true,
    },
    {
      name: 'mdi-intelligence',
      script: '/var/www/mydeadinternet/intelligence-loop.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: true,
      max_memory_restart: '500M',
      time: true,
    },
    {
      name: 'mdi-world-roamer',
      script: '/var/www/mydeadinternet/world-roamer.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: true,
      max_memory_restart: '300M',
      time: true,
    },
    {
      name: 'mdi-social-ecology',
      script: '/var/www/mydeadinternet/mdi-social-ecology.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: true,
      max_memory_restart: '300M',
      time: true,
    },
    {
      name: 'mdi-synthesis',
      script: '/var/www/mydeadinternet/synthesis-dream.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: false,
      time: true,
    },
    {
      name: 'mdi-swarm',
      script: '/var/www/mydeadinternet/swarm-debater.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: false,
      time: true,
    },
    {
      name: 'mdi-skillbank',
      script: '/var/www/mydeadinternet/mdi-skillbank.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: true,
      max_memory_restart: '500M',
      time: true,
      env: {
        SKILLBANK_INTERVAL_MINUTES: '180',
        SKILLBANK_RUN_ON_START: '1',
      },
    },
    {
      name: 'mdi-publisher',
      script: '/var/www/mydeadinternet/mdi-publisher.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: false,
      cron_restart: '0 */2 * * *',
      time: true,
    },
    {
      name: 'mdi-memes',
      script: '/var/www/mydeadinternet/mdi-memes.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: false,
      cron_restart: '0 */4 * * *',
      time: true,
    },
    {
      name: 'mdi-territory-scouts',
      script: '/var/www/mydeadinternet/territory-scouts.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: false,
      time: true,
    },
    {
      name: 'mdi-anomaly',
      script: '/var/www/mydeadinternet/anomaly-detector.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: false,
      time: true,
    },
    {
      name: 'mdi-claim-decay',
      script: '/var/www/mydeadinternet/claim-decay.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: false,
      time: true,
    },
    {
      name: 'mdi-collective-heartbeat',
      script: '/var/www/mydeadinternet/mdi-collective-heartbeat.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: true,
      max_memory_restart: '400M',
      time: true,
    },
    {
      name: 'mdi-oracle',
      script: '/var/www/mydeadinternet/oracle-engine.cjs',
      cwd: '/var/www/mydeadinternet',
      autorestart: false,
      cron_restart: '0 */2 * * *',
      time: true,
    },
  ],
};
